name: Build/Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # platform: [windows-latest]
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - uses: Swatinem/rust-cache@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
          check-latest: true
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

      - name: Install app dependencies from lockfile and build web
        # NOTE: comment out && npm run build if frontend does not have build script
        run: npm install && npm run build

      - name: tauri-build
        uses: JonasKruckenberg/tauri-build@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "HyaiPaper v__VERSION__"
          releaseBody: |
            ${{steps.build_changelog.outputs.changelog}}
            See the assets to download this version and install.
          releaseDraft: true
          prerelease: false
